# Generated by Django 5.2.17 on 2026-08-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_measurement"),
    ]

    operations = [
        migrations.AddField(
            model_name="measurement",
            name="photo_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="measurement",
            name="thumbnail_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
    ]
