# Generated by Django 5.2.8 on 2026-08-11 17:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_measurement_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("weight", "Weight"),
                            ("chest", "Chest"),
                            ("waist", "Waist"),
                            ("hips", "Hips"),
                            ("biceps", "Biceps"),
                            ("thigh", "Thigh"),
                            ("calf", "Calf"),
                            ("body_fat_pct", "Body fat %"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "target_value",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=6,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(1000),
                        ],
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("decrease", "Decrease"), ("increase", "Increase")],
                        max_length=8,
                    ),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                ("is_completed", models.BooleanField(default=False)),
                ("description", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["is_completed", "-created_at"],
            },
        ),
    ]
