# Generated by Django 5.2.17 on 2026-08-12 12:16
# P9: height becomes a once-set profile attribute on CustomUser. Backfill each
# user's ``height_cm`` from their most recent measurement carrying a height, then
# capture stops collecting it (BMI sources it from here). ORM only — no raw SQL.

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def backfill_height(apps, schema_editor):
    """Seed ``height_cm`` from each user's latest measured height."""
    CustomUser = apps.get_model("core", "CustomUser")
    Measurement = apps.get_model("core", "Measurement")
    for user in CustomUser.objects.all():
        latest_height = (
            Measurement.objects.filter(user=user, height__isnull=False)
            .order_by("-measured_at", "-created_at")
            .values_list("height", flat=True)
            .first()
        )
        if latest_height is not None:
            user.height_cm = latest_height
            user.save(update_fields=["height_cm"])


def noop_reverse(apps, schema_editor):
    """Reverse is a no-op — the column drop (RemoveField) discards the values."""


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_message_and_measurement_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="height_cm",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("50")),
                    django.core.validators.MaxValueValidator(Decimal("250")),
                ],
            ),
        ),
        migrations.RunPython(backfill_height, noop_reverse),
    ]
